Fixed handling of Unicode string in ca_certs parm of WBEMConnection on py2
Details:

* When invoking M2Crypto's ctx.load_verify_locations() method, any provided
  paths in the 'cafile' or 'capath' parameters need to be byte strings. If
  they are Unicode strings, M2Crypto raises:
    TypeError: in method 'ssl_ctx_load_verify_locations',
      argument 3 of type 'char const *'
  which is probably caused by the interface code generated by swig.

  This change converts the path names to byte strings before passing them
  to the method.

* Clarified in the description of the ca_certs parameter of WBEMConnection
  that path names may be any type of string (byte string or unicode string).

Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>