Docs: Fixes in doc build
Details:

* Fixed that the make commands for doc builds ignored errors returned by
  sphinx-build due to the popd command following it. Since this is done in a
  sub-shell, the popd was not needed anyway, and this issue could be addressed
  by removing the popd command so that the exit code of sphinx-build becomes
  the exit code of the shell command and causes make to stop as intended.

* Fixed issue #2983 which caused the doc build to fail with an exception.
  That happened only with Sphinx 6.x where Sphinx now requires that
  the caption field in extlink definitions has exactly one %s marker.
  Fixed that by adding the %s marker in the extlink definitions in
  conf.py.

* Changed target directory of man build ('make man') to build_doc/man/man1
  so that the man command can find it: 'man -m build_doc/man pywbem'.

* Removed the Sphinx warning about language None by setting it to 'en'.

* Increased minimum version of docutils to 0.16 on Python>=3.11 to fix
  ValueError: invalid mode: 'rU' in docutils.

* Fixed missing back quote in a docstring in
  pywbem_mock/_instancewriteprovider.py.

Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>