Fixed Travis errors with use of imnplementation_name marker
Details:

* A recent change to dev-requirements.txt and minimum-constraints.txt
  in PR #2200 introduced the use of the implementation_name env marker
  for the typed-ast package. On Python 3.4 with minimal package levels,
  using that env marker causes make installtest to fail when test_install.sh
  attempts to upgrade setuptools, with Pip raising this exception in its
  vendored distlib:
    SyntaxError: invalid expression: implementation_name
  The Pip version that does that is Pip 8.0.0. Pip 9.0.1 supports
  the implementation_name env marker. The reason test_install.sh upgrades
  pip after setuptools is that earlier on, upgrading pip first caused
  a permission error.

  This change removes the use of the implementation_name env marker for the
  typed-ast package, and goes back to upgrading pip first. The permission
  error did not show up again.

Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>