Added locale settings ti fix issue with 'safety' command on CygWin
Details:

* The trigger for this fix was that the 'safety' command failed on
  CygWin on Python 3.x, where the Click package raised the following
  exception:

    RuntimeError: Click will abort further execution because Python 3 was
    configured to use ASCII as encoding for the environment. Consult
    https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.
    This system supports the C.UTF-8 locale which is recommended.
    You might be able to resolve your issue by exporting the
    following environment variables:
      export LC_ALL=C.UTF-8
      export LANG=C.UTF-8

  This change fixes that by setting these two environment variables
  as proposed, when the Appveyor environment is a UNIX-like environment.

Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>